repos:
  # Run the linter.
  - repo: local
    hooks:
      - id: ruff-check
        args: [--fix]
        name: ruff-check
        entry: ruff check
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies: [ruff]

  # Run the formatter.
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies: [ruff]

  # Type checking with MyPy
  - repo: local
    hooks:
      - id: mypy-check
        name: mypy-check
        entry: mypy
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies:
          - mypy
          - pydantic-settings
          - sqlmodel
          - fastapi
