repos:
  # Run the linter.
  - repo: local
    hooks:
      - id: ruff-check
        args: [--fix]
        name: ruff-check
        entry: ruff check
        language: system
        types: [python]
        pass_filenames: false

  # Run the formatter.
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]
        pass_filenames: false

  # Type checking with MyPy
  - repo: local
    hooks:
      - id: mypy-check
        name: mypy-check
        entry: mypy
        language: system
        types: [python]
        pass_filenames: false
